typography_spectrum: 0.4617021
color:
  saturation: 0.6624077307060361
  brandStrength: 0.8416965131182224
  rhythmicContrast: 0.3010823235381395
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  lightness: 0.8790699825622141
opengraph:
  appId: 'https://www.facebook.com/diego.poncina'
  type: Person
layout_spectrum: 0.9404255
author:
  name: diego poncina
  email: diego@diegoponcina.it
  url: www.diegoponcina.it
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ce810d4b-bb96-47c4-ab85-c4364313da56.png
name: diegoponcina.it
navigation:
  - name: my mission
    url: 'http://www.vitadiluce.it'
    type: external
  - name: 'Ci siamo, Chi sono...'
    id: b5b8fda6-ebc4-4620-90e2-e7774b2630d8
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5e612209-3555-4bc0-a4a7-e746ca930b70.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Welcome in my IA xperience
description: Benvenuti nella mia Esperienza in Intelligenza Artificiale
