typography_spectrum: 0.4617021
color:
  saturation: 0.6624077307060361
  brandStrength: 0.8416965131182224
  rhythmicContrast: 0.3010823235381395
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  lightness: 0.8790699825622141
opengraph:
  appId: diego.poncina
layout_spectrum: 0.9404255
author:
  name: diego poncina
  email: diego@diegoponcina.it
  url: www.diegoponcina.it
name: diegoponcina.it
navigation:
  - name: my mission
    url: 'http://www.vitadiluce.it'
    type: external
  - name: 'Ci siamo, Chi sono...'
    id: b5b8fda6-ebc4-4620-90e2-e7774b2630d8
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Welcome in my IA xperience
description: Benvenuti nella mia Esperienza in Intelligenza Artificiale
